import { MenuItem, Order, Table, Staff, InventoryItem, Reservation } from '@/types/index';

export const mockMenuItems: MenuItem[] = [
  // PIZZAS
  {
    id: '1',
    name: 'Margherita Pizza',
    description: 'Fresh tomatoes, mozzarella, basil & olive oil - Classic Italian Style',
    category: 'Pizzas',
    price: 16.99,
    prepTime: 12,
    available: true,
    spicy: false,
    vegan: false,
    glutenFree: false,
    calories: 320,
    emoji: '🍅',
    image: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=400&h=400&fit=crop',
  },
  {
    id: '2',
    name: 'Pepperoni Pizza',
    description: 'Classic pepperoni slices with melted mozzarella & tomato sauce',
    category: 'Pizzas',
    price: 18.99,
    prepTime: 12,
    available: true,
    spicy: false,
    vegan: false,
    glutenFree: false,
    calories: 380,
    emoji: '🔥',
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07f4ee?w=400&h=400&fit=crop',
  },
  {
    id: '3',
    name: 'Veggie Pizza',
    description: 'Fresh vegetables - mushrooms, peppers, onions, olives & broccoli',
    category: 'Pizzas',
    price: 17.99,
    prepTime: 12,
    available: true,
    spicy: false,
    vegan: true,
    glutenFree: false,
    calories: 310,
    emoji: '🥒',
    image: 'https://images.unsplash.com/photo-1511689915489-a1a238a7f7d0?w=400&h=400&fit=crop',
  },
  {
    id: '4',
    name: 'Spicy Jalapeño Pizza',
    description: 'Green jalapeños, hot pepperoni, onions & extra garlic - Very Spicy!',
    category: 'Pizzas',
    price: 19.99,
    prepTime: 12,
    available: true,
    spicy: true,
    vegan: false,
    glutenFree: false,
    calories: 400,
    emoji: '🌶️',
    image: 'https://images.unsplash.com/photo-1585238341710-4dd0bd180d8d?w=400&h=400&fit=crop',
  },
  
  // MAIN COURSES
  {
    id: '5',
    name: 'Grilled Salmon',
    description: 'Fresh Atlantic salmon with lemon butter sauce',
    category: 'Steaks',
    price: 28.99,
    prepTime: 15,
    available: true,
    spicy: false,
    vegan: false,
    glutenFree: true,
    calories: 450,
    emoji: '🐟',
  },
  {
    id: '6',
    name: 'Pad Thai',
    description: 'Thai stir-fried noodles with shrimp and peanuts',
    category: 'Steaks',
    price: 18.99,
    prepTime: 10,
    available: true,
    spicy: true,
    vegan: false,
    glutenFree: false,
    calories: 380,
    emoji: '🍜',
  },
  {
    id: '7',
    name: 'Ribeye Steak',
    description: '14oz premium aged ribeye with garlic butter',
    category: 'Steaks',
    price: 42.99,
    prepTime: 18,
    available: true,
    spicy: false,
    vegan: false,
    glutenFree: true,
    calories: 680,
    emoji: '🥩',
  },
  {
    id: '8',
    name: 'Chicken Alfredo',
    description: 'Creamy pasta with grilled chicken and parmesan',
    category: 'Breads',
    price: 22.99,
    prepTime: 14,
    available: true,
    spicy: false,
    vegan: false,
    glutenFree: false,
    calories: 520,
    emoji: '🍝',
  },
  {
    id: '9',
    name: 'Vegan Buddha Bowl',
    description: 'Quinoa, roasted vegetables, and tahini dressing',
    category: 'Salads',
    price: 15.99,
    prepTime: 8,
    available: true,
    spicy: false,
    vegan: true,
    glutenFree: true,
    calories: 420,
    emoji: '🥗',
  },
  {
    id: '10',
    name: 'Fish & Chips',
    description: 'Crispy battered cod with fries and tartar sauce',
    category: 'Burgers',
    price: 19.99,
    prepTime: 12,
    available: true,
    spicy: false,
    vegan: false,
    glutenFree: false,
    calories: 580,
    emoji: '🍟',
  },

  // APPETIZERS
  {
    id: '11',
    name: 'Caesar Salad',
    description: 'Crisp romaine with parmesan and croutons',
    category: 'Salads',
    price: 12.99,
    prepTime: 5,
    available: true,
    spicy: false,
    vegan: false,
    glutenFree: true,
    calories: 250,
    emoji: '🥗',
  },
  {
    id: '12',
    name: 'Bruschetta',
    description: 'Toasted bread with tomatoes and basil',
    category: 'Breads',
    price: 8.99,
    prepTime: 3,
    available: true,
    spicy: false,
    vegan: true,
    glutenFree: false,
    calories: 180,
    emoji: '🍞',
  },
  {
    id: '13',
    name: 'Mozzarella Sticks',
    description: 'Golden fried mozzarella with marinara sauce',
    category: 'Breads',
    price: 9.99,
    prepTime: 5,
    available: true,
    spicy: false,
    vegan: false,
    glutenFree: false,
    calories: 320,
    emoji: '🧀',
  },
  {
    id: '14',
    name: 'Buffalo Wings',
    description: 'Spicy buffalo wings with blue cheese dip',
    category: 'Burgers',
    price: 13.99,
    prepTime: 8,
    available: true,
    spicy: true,
    vegan: false,
    glutenFree: true,
    calories: 420,
    emoji: '🍗',
  },
  {
    id: '15',
    name: 'Spring Rolls',
    description: 'Crispy vegetable spring rolls with sweet sauce',
    category: 'Breads',
    price: 10.99,
    prepTime: 6,
    available: true,
    spicy: false,
    vegan: true,
    glutenFree: false,
    calories: 260,
    emoji: '🥟',
  },

  // DESSERTS
  {
    id: '16',
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with molten center',
    category: 'Desserts',
    price: 9.99,
    prepTime: 7,
    available: true,
    spicy: false,
    vegan: false,
    glutenFree: false,
    calories: 520,
    emoji: '🍰',
  },
  {
    id: '17',
    name: 'Cheesecake',
    description: 'New York style cheesecake with strawberry',
    category: 'Desserts',
    price: 8.99,
    prepTime: 2,
    available: true,
    spicy: false,
    vegan: false,
    glutenFree: false,
    calories: 480,
    emoji: '🍰',
  },
  {
    id: '18',
    name: 'Tiramisu',
    description: 'Classic Italian tiramisu with mascarpone',
    category: 'Desserts',
    price: 8.99,
    prepTime: 2,
    available: true,
    spicy: false,
    vegan: false,
    glutenFree: false,
    calories: 440,
    emoji: '🍮',
  },
  {
    id: '19',
    name: 'Ice Cream Sundae',
    description: 'Vanilla ice cream with chocolate sauce and nuts',
    category: 'Desserts',
    price: 7.99,
    prepTime: 3,
    available: true,
    spicy: false,
    vegan: false,
    glutenFree: true,
    calories: 380,
    emoji: '🍦',
  },
  {
    id: '20',
    name: 'Fruit Tart',
    description: 'Fresh seasonal fruits on pastry cream',
    category: 'Desserts',
    price: 9.99,
    prepTime: 2,
    available: true,
    spicy: false,
    vegan: false,
    glutenFree: false,
    calories: 320,
    emoji: '🧁',
  },

  {
    id: '21',
    name: 'Soft Drink',
    description: 'Coca-Cola, Sprite, Fanta (250ml)',
    category: 'Drinks',
    price: 3.99,
    prepTime: 1,
    available: true,
    spicy: false,
    vegan: true,
    glutenFree: true,
    calories: 140,
    emoji: '🥤',
  },
  {
    id: '22',
    name: 'Fresh Orange Juice',
    description: 'Freshly squeezed orange juice (300ml)',
    category: 'Drinks',
    price: 5.99,
    prepTime: 2,
    available: true,
    spicy: false,
    vegan: true,
    glutenFree: true,
    calories: 110,
    emoji: '🧃',
  },
  {
    id: '23',
    name: 'Iced Tea',
    description: 'Refreshing iced tea with lemon (400ml)',
    category: 'Drinks',
    price: 4.99,
    prepTime: 1,
    available: true,
    spicy: false,
    vegan: true,
    glutenFree: true,
    calories: 50,
    emoji: '🍵',
  },
  
  {
    id: '24',
    name: 'Classic Cheeseburger',
    description: 'Juicy beef patty with cheddar, lettuce, tomato',
    category: 'Burgers',
    price: 16.99,
    prepTime: 10,
    available: true,
    spicy: false,
    vegan: false,
    glutenFree: false,
    calories: 520,
    emoji: '🍔',
  },
  {
    id: '25',
    name: 'Tandoori Chicken',
    description: 'Marinated Indian chicken with rice and naan',
    category: 'Steaks',
    price: 21.99,
    prepTime: 16,
    available: true,
    spicy: true,
    vegan: false,
    glutenFree: true,
    calories: 480,
    emoji: '🍗',
  },
  {
    id: '26',
    name: 'Vegetable Stir Fry',
    description: 'Mixed vegetables in garlic and ginger sauce',
    category: 'Salads',
    price: 14.99,
    prepTime: 10,
    available: true,
    spicy: false,
    vegan: true,
    glutenFree: true,
    calories: 320,
    emoji: '🥘',
  },
  {
    id: '27',
    name: 'Lobster Bisque',
    description: 'Creamy lobster soup with croutons',
    category: 'Breads',
    price: 14.99,
    prepTime: 8,
    available: true,
    spicy: false,
    vegan: false,
    glutenFree: true,
    calories: 280,
    emoji: '🍲',
  },
  {
    id: '28',
    name: 'Thai Green Curry',
    description: 'Fragrant green curry with coconut and vegetables',
    category: 'Steaks',
    price: 19.99,
    prepTime: 12,
    available: true,
    spicy: true,
    vegan: true,
    glutenFree: true,
    calories: 410,
    emoji: '🍛',
  },
  {
    id: '29',
    name: 'Grilled Lamb Chops',
    description: 'Succulent lamb chops with mint sauce',
    category: 'Steaks',
    price: 34.99,
    prepTime: 20,
    available: true,
    spicy: false,
    vegan: false,
    glutenFree: true,
    calories: 620,
    emoji: '🍖',
  },
  {
    id: '30',
    name: 'Sushi Platter',
    description: 'Assorted fresh sushi rolls with wasabi',
    category: 'Salads',
    price: 26.99,
    prepTime: 8,
    available: true,
    spicy: false,
    vegan: false,
    glutenFree: false,
    calories: 380,
    emoji: '🍣',
  },
  {
    id: '31',
    name: 'Chocolate Mousse',
    description: 'Rich and airy chocolate mousse dessert',
    category: 'Desserts',
    price: 7.99,
    prepTime: 2,
    available: true,
    spicy: false,
    vegan: false,
    glutenFree: true,
    calories: 420,
    emoji: '🍫',
  },
  {
    id: '32',
    name: 'Espresso Coffee',
    description: 'Strong Italian espresso (80ml)',
    category: 'Drinks',
    price: 3.49,
    prepTime: 2,
    available: true,
    spicy: false,
    vegan: true,
    glutenFree: true,
    calories: 5,
    emoji: '☕',
  },
];

export const mockTables: Table[] = [
  { id: 'T1', number: 1, capacity: 2, status: 'available', location: 'Window' },
  { id: 'T2', number: 2, capacity: 2, status: 'occupied', currentOrderId: 'O1', location: 'Window' },
  { id: 'T3', number: 3, capacity: 4, status: 'available', location: 'Center' },
  { id: 'T4', number: 4, capacity: 4, status: 'occupied', currentOrderId: 'O2', location: 'Center' },
  { id: 'T5', number: 5, capacity: 6, status: 'reserved', reservedBy: 'John Smith', reservedUntil: new Date(Date.now() + 3600000), location: 'Private' },
  { id: 'T6', number: 6, capacity: 2, status: 'dirty', location: 'Bar' },
  { id: 'T7', number: 7, capacity: 8, status: 'available', location: 'Private' },
  { id: 'T8', number: 8, capacity: 4, status: 'occupied', currentOrderId: 'O3', location: 'Patio' },
];

export const mockStaff: Staff[] = [
  {
    id: 'S1',
    name: 'Maria Garcia',
    role: 'manager',
    email: 'maria@restaurant.com',
    phone: '+1-555-0101',
    status: 'active',
    joinDate: new Date('2020-01-15'),
  },
  {
    id: 'S2',
    name: 'James Chef',
    role: 'chef',
    email: 'james@restaurant.com',
    phone: '+1-555-0102',
    status: 'active',
    joinDate: new Date('2020-06-10'),
  },
  {
    id: 'S3',
    name: 'Sarah Johnson',
    role: 'waiter',
    email: 'sarah@restaurant.com',
    phone: '+1-555-0103',
    status: 'active',
    joinDate: new Date('2021-03-22'),
    shift: 'morning',
  },
  {
    id: 'S4',
    name: 'Mike Wilson',
    role: 'waiter',
    email: 'mike@restaurant.com',
    phone: '+1-555-0104',
    status: 'on-break',
    joinDate: new Date('2021-09-05'),
    shift: 'afternoon',
  },
  {
    id: 'S5',
    name: 'Alex Chen',
    role: 'cashier',
    email: 'alex@restaurant.com',
    phone: '+1-555-0105',
    status: 'active',
    joinDate: new Date('2022-01-18'),
  },
  {
    id: 'S6',
    name: 'David Brown',
    role: 'delivery',
    email: 'david@restaurant.com',
    phone: '+1-555-0106',
    status: 'active',
    joinDate: new Date('2023-02-14'),
  },
];

export const mockInventory: InventoryItem[] = [
  {
    id: 'INV1',
    name: 'Salmon Fillet',
    category: 'Proteins',
    quantity: 45,
    unit: 'lb',
    reorderLevel: 20,
    cost: 12.5,
    supplier: 'Fresh Seafood Inc',
    lastRestocked: new Date(Date.now() - 86400000),
  },
  {
    id: 'INV2',
    name: 'Beef Ribeye',
    category: 'Proteins',
    quantity: 8,
    unit: 'lb',
    reorderLevel: 15,
    cost: 18,
    supplier: 'Prime Beef Co',
    lastRestocked: new Date(Date.now() - 172800000),
  },
  {
    id: 'INV3',
    name: 'Mozzarella Cheese',
    category: 'Dairy',
    quantity: 120,
    unit: 'lb',
    reorderLevel: 50,
    cost: 4.5,
    supplier: 'Italian Imports',
    lastRestocked: new Date(Date.now() - 86400000),
  },
  {
    id: 'INV4',
    name: 'Olive Oil',
    category: 'Pantry',
    quantity: 25,
    unit: 'L',
    reorderLevel: 10,
    cost: 8,
    supplier: 'Mediterranean Foods',
    lastRestocked: new Date(Date.now() - 259200000),
  },
  {
    id: 'INV5',
    name: 'Tomatoes',
    category: 'Produce',
    quantity: 5,
    unit: 'lb',
    reorderLevel: 30,
    cost: 1.2,
    supplier: 'Local Farm Fresh',
    lastRestocked: new Date(Date.now() - 172800000),
  },
];

export const mockOrders: Order[] = [
  {
    id: 'O1',
    tableId: 'T2',
    customerName: 'Alice Thompson',
    items: [
      { id: 'OI1', menuItemId: '1', quantity: 1, status: 'ready' },
      { id: 'OI2', menuItemId: '6', quantity: 2, status: 'ready' },
    ],
    status: 'ready',
    createdAt: new Date(Date.now() - 900000),
    updatedAt: new Date(Date.now() - 300000),
    dineInType: 'dine-in',
    totalAmount: 48.97,
    paymentStatus: 'pending',
    preparationStartedAt: new Date(Date.now() - 900000),
  },
  {
    id: 'O2',
    tableId: 'T4',
    customerName: 'Robert Martinez',
    items: [
      { id: 'OI3', menuItemId: '4', quantity: 2, status: 'preparing' },
      { id: 'OI4', menuItemId: '3', quantity: 1, status: 'ready' },
    ],
    status: 'preparing',
    createdAt: new Date(Date.now() - 600000),
    updatedAt: new Date(Date.now() - 150000),
    dineInType: 'dine-in',
    totalAmount: 48.97,
    paymentStatus: 'pending',
    preparationStartedAt: new Date(Date.now() - 450000),
  },
  {
    id: 'O3',
    tableId: 'T8',
    customerName: 'Emma Wilson',
    items: [
      { id: 'OI5', menuItemId: '7', quantity: 1, status: 'preparing' },
      { id: 'OI6', menuItemId: '2', quantity: 1, status: 'pending' },
    ],
    status: 'pending',
    createdAt: new Date(Date.now() - 120000),
    updatedAt: new Date(Date.now() - 120000),
    dineInType: 'dine-in',
    totalAmount: 59.98,
    paymentStatus: 'pending',
  },
];

export const mockReservations: Reservation[] = [
  {
    id: 'R1',
    customerName: 'John Smith',
    customerPhone: '+1-555-0201',
    numberOfGuests: 4,
    reservedDate: new Date(Date.now() + 86400000),
    reservedTime: '19:00',
    specialRequests: 'Window seating preferred',
    status: 'confirmed',
  },
  {
    id: 'R2',
    customerName: 'Lisa Anderson',
    customerPhone: '+1-555-0202',
    numberOfGuests: 2,
    reservedDate: new Date(Date.now() + 172800000),
    reservedTime: '20:30',
    status: 'confirmed',
  },
];
